name: "Build and run stress tests"
description: "Action for stress testing"

inputs:
  arch:
    description: 'grayskull or wormhole_b0'
    required: true
  dispatch:
    description: 'fast or slow'
    required: true
  machine:
    description: 'Virtual machine or Bare metal'
    required: true

runs:
  using: "composite"
  steps:
    - uses: tenstorrent-metal/metal-workflows/.github/actions/checkout-with-submodule-lfs@2.0.0
    - name: Set up dynamic env vars for build
      run: |
        echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
    - name: Build tt-metal and libs
      run: make build
    - name: Build tt-metal CPP tests
      run: make tests
    - name: Run pre/post regression tests in a loop
      run: |
        source build/python_env/bin/activate
        ./tests/scripts/run_tests.sh --tt-arch ${{ arch }} --pipeline-type stress_post_commit --dispatch-mode ${{ dispatch }}
    - name: Upload watcher log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: watcher-log-${{ arch }}-${{ machine }}
        path: generated/watcher/watcher.log
