name: "[post-commit] Build C++ binaries with all configs"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-lib:
    strategy:
      matrix:
        type: [ Debug, Release, RelWithDebInfo ]
        arch: [grayskull, wormhole_b0, blackhole]
        os: [ubuntu-20.04]
    env:
      ARCH_NAME: ${{ matrix.arch }}
      CONFIG: ${{ matrix.type }}
      # So we can get all the makefile output we want
      VERBOSE: 1
    runs-on: ${{ matrix.os }}
    name: cmake build ${{ matrix.type }} ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: false
      - uses: ./.github/actions/install-metal-deps
        with:
          os: ubuntu-20.04
      - uses: ./.github/actions/install-metal-dev-deps
        with:
          os: ubuntu-20.04
      - name: Set up dynamic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - name: Build tt-metal libraries
        run: |
          cmake -B build -G Ninja -DCMAKE_CXX_COMPILER=clang++-17
          cmake --build build
      - name: Build tt-metal C++ tests
        run: |
          cmake --build build --target tests
      - uses: ./.github/actions/slack-report
        if: ${{ failure() }}
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          owner: U0593J2RQRZ # Bill Teng
