name: "[internal] Build cmake"

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  build-cmake:
    strategy:
      matrix:
        arch: [grayskull, wormhole_b0]
    name: CMake Build
    env:
      TT_METAL_ENV: ${{ vars.TT_METAL_ENV }}
      ARCH_NAME: ${{ matrix.arch }}
      LD_LIBRARY_PATH: ${{ github.workspace }}/build/lib
    runs-on: build
    steps:
      - uses: tenstorrent-metal/metal-workflows/.github/actions/checkout-with-submodule-lfs@v2.0.0
        with:
          ref: vtangTT/cmake_metal_eager
      - name: Set up dynamic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - name: CMake CI Build - Generate build files
        run: |
          rm -rf build
          cmake -DCMAKE_BUILD_TYPE=ci -DCONFIG=ci -B build
      - name: CMake CI Build - Build metal + eager
        timeout-minutes: 15
        run: |
          cmake --build build -- -j8
      - name: CMake CI Build - Build tests
        timeout-minutes: 10
        run: |
          cmake --build build --target tests -- -j8
