name: "Build TTMetal artifacts"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-artifact:
    strategy:
      matrix:
        arch: ["grayskull", "wormhole_b0"]
    env:
      TT_METAL_ENV: ${{ vars.TT_METAL_ENV }}
      ARCH_NAME: ${{ matrix.arch }}
      CONFIG: ci
    environment: dev
    runs-on: build
    steps:
      - uses: tenstorrent-metal/metal-workflows/.github/actions/checkout-with-submodule-lfs@v2.0.0
      - name: Set up dyanmic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - name: Build tt-metal and libs
        run: |
          make build PYTHON_ENV=$HOME/python_env
      - uses: actions/upload-artifact@v4
        with:
          name: TTMetal_build_${{ matrix.arch }}
          path: |
            build/hw
            build/lib
            tt_eager/tt_lib/*.so
            ttnn/ttnn/*.so
