name: "Build tt-metal artifacts"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-artifact:
    strategy:
      matrix:
        arch: ["grayskull", "wormhole_b0"]
    env:
      TT_METAL_ENV: ${{ vars.TT_METAL_ENV }}
      ARCH_NAME: ${{ matrix.arch }}
      SILENT: 0
      VERBOSE: 1
    environment: dev
    runs-on: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up dynamic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - uses: ./.github/actions/install-python-deps
      - name: Build tt-metal and libs
        run: |
          cmake -B build
          cmake --build build --target tests -- -j`nproc`
          cmake --build build --target metal-install
      - name: 'Tar files'
        run: tar -cvf ttm_${{ matrix.arch }}.tar build/hw build/lib tt_eager/tt_lib/*.so ttnn/ttnn/*.so build/programming_examples build/test build/tools
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: TTMetal_build_${{ matrix.arch }}
          path: ttm_${{ matrix.arch }}.tar
