name: "[post-commit] Build C++ binaries with all configs"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-gh:
    strategy:
      matrix:
        config: [debug, release, ci]
        arch: [grayskull, wormhole_b0]
        os: [ubuntu-20.04]
    env:
      ARCH_NAME: ${{ matrix.arch }}
      CONFIG: ${{ matrix.config }}
      # So we can get all the makefile output we want
      SILENT: 0
    runs-on: ${{ matrix.os }}
    steps:
      - uses: tenstorrent-metal/metal-workflows/.github/actions/checkout-with-submodule-lfs@v2.0.0
      - uses: ./.github/actions/install-metal-deps
        with:
          os: ubuntu-20.04
      - uses: ./.github/actions/install-metal-dev-deps
        with:
          os: ubuntu-20.04
      - name: Set up dynamic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - name: Build tt-metal libraries
        run: make build
      - name: Build tt-metal tests
        # Does not work yet
        if: ${{ matrix.config != 'release' }}
        run: make tests
  build-self-hosted:
    strategy:
      matrix:
        config: [assert]
        arch: [grayskull, wormhole_b0]
    env:
      ARCH_NAME: ${{ matrix.arch }}
      CONFIG: ${{ matrix.config }}
      # So we can get all the makefile output we want
      SILENT: 0
    runs-on: build
    steps:
      - uses: tenstorrent-metal/metal-workflows/.github/actions/checkout-with-submodule-lfs@v2.0.0
      - name: Set up dynamic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - name: Build tt-metal libraries
        run: make build
      - name: Build tt-metal tests
        run: make tests
