name: "cleanup-workflow"

on:
  workflow_dispatch:

jobs:
  build-and-unit-tests-fast-dispatch:
    strategy:
      # Do not fail-fast because we need to ensure all tests go to completion
      # so we try not to get hanging machines
      fail-fast: false
      matrix:
        runner-info: [
          {arch: grayskull, runs-on: ["tt-metal-ci-vm4"]},
          # N150
          {arch: wormhole_b0, runs-on: ["tt-metal-ci-vm-32"]},
          # N300
          {arch: wormhole_b0, runs-on: ["tt-metal-ci-vm-33"]},
        ]
    env:
      TT_METAL_ENV: ${{ vars.TT_METAL_ENV }}
      ARCH_NAME: ${{ matrix.runner-info.arch }}
    environment: dev
    runs-on: ${{ matrix.runner-info.runs-on }}
    steps:
      - uses: tenstorrent-metal/metal-workflows/.github/actions/checkout-with-submodule-lfs@main
      - name: Set up dynamic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - name: Build tt-metal and libs
        run: make build
      - name: Build tt-metal CPP tests
        run: make tests
      # - name: Run pre/post regression tests
      #   timeout-minutes: 120
      #   run: |
      #     source build/python_env/bin/activate
      #     ./tests/scripts/run_tests.sh --tt-arch $ARCH_NAME --pipeline-type post_commit --dispatch-mode fast
