name: "Release Docs: package the docs and publish to Docs the repo"
on:
  workflow_dispatch:

jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
  build-docs:
    needs: build-artifact
    uses: ./.github/workflows/docs-deployment.yaml
    secrets: inherit