name: "[internal] syseng asset upgrade mmio timeout test"

on:
  workflow_dispatch:
  push:
    branches:
      - "tpatel/t3k-1G"

jobs:
  single-chip:
    strategy:
      # Do not fail-fast because we need to ensure all tests go to completion
      # so we try not to get hanging machines
      fail-fast: false
      matrix:
        runner-info: [
          # N300 2x4
          {name: "n300-2x4", arch: wormhole_b0, runs-on: ["arch-wormhole_b0", "multi-chip-num-pcie-4", "multi-chip-num-chips-8", "issue-miw-162"]},
        ]
    env:
      TT_METAL_ENV: ${{ vars.TT_METAL_ENV }}
      ARCH_NAME: ${{ matrix.runner-info.arch }}
      CONFIG: ci
    environment: dev
    runs-on: ${{ matrix.runner-info.runs-on }}
    steps:
      - uses: tenstorrent-metal/metal-workflows/.github/actions/checkout-with-submodule-lfs@v2.0.0
      - name: Set up dyanmic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - name: Build tt-metal and libs
        run: make build
      - name: Build tt-metal CPP tests
        run: make tests
      - name: Run pre/post regression tests
        timeout-minutes: 60
        run: |
          source build/python_env/bin/activate
          tt-smi-metal -r 0 ; for i in {1..20}; do tt-smi-metal -r 0 && (timeout 10 ./build/test/tt_metal/unit_tests_fast_dispatch || true) ; tt-smi-metal -r 0; done; ./build/test/tt_metal/unit_tests_fast_dispatch
          tt-smi-metal -r 0 ; for i in {1..20}; do tt-smi-metal -r 0 && (TT_METAL_SLOW_DISPATCH_MODE=1 timeout 10 ./build/test/tt_metal/unit_tests || true) ; tt-smi-metal -r 0; done; TT_METAL_SLOW_DISPATCH_MODE=1 ./build/test/tt_metal/unit_tests
